name: ecantina
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.4

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the cupertino Icons font to your application.
  # Use with the cupertinoIcons class for IOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^2.17.0
  firebase_storage: ^11.2.8
  firebase_auth: ^4.10.1
  cloud_firestore: ^4.9.3
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
